# Generated by Django 4.2.14 on 2024-08-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GujaratHighCourtJudge',
            fields=[
                ('sl_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=50)),
                ('date_of_appointment_as_addl_judge', models.DateField()),
                ('date_of_appointment_as_pmt_judge', models.DateField()),
                ('date_of_retirement', models.DateField()),
                ('remarks', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('sl_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date_of_appointment', models.DateField()),
                ('date_of_retirement', models.DateField()),
                ('remarks', models.CharField(max_length=255)),
            ],
        ),
    ]
