# Generated by Django 4.2.14 on 2024-08-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gujarathighcourtjudge',
            name='date_of_appointment_as_addl_judge',
            field=models.DateField(null=True),
        ),
    ]
