# Generated by Django 4.2.14 on 2024-08-27 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judges', '0003_alter_gujarathighcourtjudge_date_of_appointment_as_addl_judge_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Judge',
            new_name='SupremeCourtJudge',
        ),
    ]
